/**
 * A recipe: one kind of service a project can be made of — a Node app, a database —
 * written once, used by every project that names it.
 *
 * A recipe is DATA. A project names it and gives typed parameter values; it never
 * supplies an image, a flag or a path through a recipe. Parameter types are few and
 * bounded, so what a recipe renders is what the recipe itself could have written.
 *
 * Recipes follow the operator's conventions: data in the project (named volumes, bound by
 * octopod to `.octopod/data/`), nothing owned by root (a built image's user moved to the
 * operator's uid, or the service run as the operator), no dependency installed in an
 * image, services of an app in the `dev` profile.
 */
import { z } from 'zod';

/** Service names and parameter idents: safe in compose keys, hostnames and env. */
export const IDENT = /^[a-z][a-z0-9-]{0,30}$/;

const Ident = z.string().regex(IDENT, 'must match /^[a-z][a-z0-9-]{0,30}$/');
/** A value of a `set` param: a name like `pdo_mysql`, never a space or a shell character. */
const Word = z.string().regex(/^[a-z][a-z0-9_-]{0,63}$/, 'must match /^[a-z][a-z0-9_-]{0,63}$/');

export const ParamSpecSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('enum'), values: z.array(z.string().max(64)).min(1), default: z.string().optional() }).strict(),
  z.object({ type: z.literal('ident'), default: z.string().regex(IDENT).optional() }).strict(),
  z.object({ type: z.literal('int'), min: z.number().int(), max: z.number().int(), default: z.number().int().optional() }).strict(),
  z.object({ type: z.literal('bool'), default: z.boolean().optional() }).strict(),
  /** Several of the values the recipe lists (PHP extensions, say): rendered space-separated. */
  z.object({ type: z.literal('set'), values: z.array(Word).min(1).max(128), default: z.array(Word).max(128).optional() }).strict(),
  /** Generated by octopod, kept in its state, never supplied by the project. */
  z.object({ type: z.literal('secret'), bytes: z.number().int().min(16).max(64).default(24) }).strict(),
]);

export type ParamSpec = z.infer<typeof ParamSpecSchema>;

export const RecipeSchema = z
  .object({
    title: z.string().min(1).max(120),
    /** One line a reader (or a model) reads to choose. */
    summary: z.string().min(1).max(400),
    /**
     * Image reference. A moving tag is accepted only with `unpinned: true`, visibly. It may
     * name an enum param (`php:{{params.php}}-fpm`): a version among the few the recipe lists.
     */
    image: z.string().min(1).max(400),
    unpinned: z.boolean().default(false),
    /**
     * Build on top of `image` from the recipe folder's `Dockerfile`. octopod passes
     * BASE_IMAGE, UID, GID and USER_NAME (the project's name) as build arguments; the build
     * context holds the Dockerfile alone — nothing of the project goes to the daemon.
     */
    build: z.boolean().default(false),
    /**
     * More build arguments, from the recipe's params (`{{params.x}}`), never from its secrets:
     * a build argument stays readable in the image's history. BASE_IMAGE, UID, GID and
     * USER_NAME are octopod's.
     */
    buildArgs: z.record(z.string().regex(/^[A-Z][A-Z0-9_]*$/), z.string().max(400)).default({}),
    command: z.array(z.string().max(4_000)).max(64).optional(),
    params: z.record(Ident, ParamSpecSchema).default({}),
    /** Structural variables only (where to listen, which mode); `{{params.x}}`, `{{secrets.x}}`, `{{service}}`. */
    env: z.record(z.string().min(1), z.string().max(2_000)).default({}),
    /** Capabilities this recipe satisfies, e.g. `sql`. */
    provides: z.array(z.string().min(1).max(64)).default([]),
    /** Values other services read as `{{provider.KEY}}`. */
    exports: z.record(z.string().min(1), z.string().max(2_000)).default({}),
    requires: z
      .array(
        z
          .object({
            capability: z.string().min(1).max(64),
            env: z.record(z.string().min(1), z.string().max(2_000)),
            optional: z.boolean().default(false),
          })
          .strict(),
      )
      .default([]),
    /** Named volumes — bound by octopod to the project's `.octopod/data/`. `when`: a bool param that keeps it. */
    volumes: z.array(z.object({ name: Ident, path: z.string().min(1).max(200), when: Ident.optional() }).strict()).default([]),
    /** The project's folder, mounted at this path (e.g. `/app`). */
    workspace: z.string().regex(/^\/[A-Za-z0-9._/-]*$/).optional(),
    tmpfs: z.array(z.string().min(1).max(200)).default([]),
    readOnly: z.boolean().default(false),
    /** The port the service listens on: written as `expose`, where octopod finds it. */
    port: z.number().int().min(1).max(65535).optional(),
    /** Routed by the edge: at the project's host, or at `<subdomain>.<project>.localhost`. */
    route: z.union([z.literal(true), z.object({ subdomain: Ident }).strict()]).optional(),
    profiles: z.array(Ident).default([]),
    /**
     * A tool (phpstan, a code formatter): never started by `up`, never routed, run on demand
     * in a one-off container (`octopod shell <project> <service> -- …`).
     */
    tool: z.boolean().default(false),
    limits: z
      .object({
        memory: z.string().regex(/^\d+[mg]$/).optional(),
        cpus: z.string().regex(/^\d+(\.\d+)?$/).optional(),
        pids: z.number().int().positive().max(4096).optional(),
      })
      .strict()
      .default({}),
    /**
     * The service runs supervisord, whose configuration is `config` and whose own programs are
     * `programs`. The project's programs (`programs:` in octopod.yaml) are rendered into a
     * file mounted at /etc/octopod/programs.conf, which the configuration includes.
     */
    supervisor: z.object({ config: z.string().regex(/^\/[A-Za-z0-9._/-]*$/), programs: z.array(z.string().min(1).max(64)).default([]) }).strict().optional(),
    health: z
      .object({
        test: z.array(z.string().max(400)).min(1),
        intervalMs: z.number().int().positive().default(2_000),
        retries: z.number().int().positive().max(60).default(30),
      })
      .strict()
      .optional(),
  })
  .strict();

export type Recipe = z.infer<typeof RecipeSchema>;
